// This file is generated by `flutterfire configure`.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
// Then delete this stub and commit the generated file.
//
// STUB — replace with the real generated file before running the app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions: run `flutterfire configure` to generate '
          'the real firebase_options.dart for this platform.',
        );
    }
  }

  // ── REPLACE all values below with real ones from `flutterfire configure` ──

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3Hq9b9sOieG3yQshHyCwSMHH-fZ7KJI',
    appId: '1:244453413198:android:960a7683e61f72498c0e1f',
    messagingSenderId: '244453413198',
    projectId: 'luxihub-uk',
    storageBucket: 'luxihub-uk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDre-3Bl7UNum4t2DcVar6h6PCyb_xidSQ',
    appId: '1:244453413198:ios:ba8dd4d60d9123b08c0e1f',
    messagingSenderId: '244453413198',
    projectId: 'luxihub-uk',
    storageBucket: 'luxihub-uk.firebasestorage.app',
    iosBundleId: 'com.example.luxihubHandyman',
  );

}